# Dependabot: aktualisiert die Abh√§ngigkeiten 
# und schickt Pull Requests nach Security Fixes
# WICHTING: Limits auf Pull Requests zu setzen!!!

version: 2
updates:
      # Frontend
    - package-ecosystem: 'npm'
      directory: '/frontend'
      schedule:
          interval: 'weekly'
      open-pull-request-limit: 1
      on:
      pull_request:
        paths:
          - frontend/**
      labels: 
        - 'dependencies'
        - 'security'
      groups:
        frontend-deps: 
          patterns:
            - "*"
      # Backend
    - package-ecosystem: 'npm'
      directory: '/backend'
      schedule:
          interval: 'weekly'
      open-pull-request-limit: 1
      on:
        pull_request:
          paths:
            - backend/**
      
      labels: 
        - 'dependencies'
        - 'security'
      groups:
        backend-deps: 
          patterns:
            - "*"
      # GitHub Actions
    - package-ecosystem: 'github-actions'
      directory: "/"
      schedule:
        interval: "weekly"
      open-pull-request-limit: 1
      on:
        pull_request:
          paths:
            - .github/workflows/**
      labels:
        - 'dependencies'
        - 'ci'
      groups:
        ci-deps: 
          patterns:
            - "*"
