version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/frontend'
      shedule:
          interval: 'weekly'
    - pacakge-ecosystem: 'npm'
      directory: '/backend'
      schedule:
          interval: 'weekly'
